name: Test Deployment to Integration

on:
  push:
    branches-ignore:
      - Develop
      - main

jobs:
  validate-branch-to-int-org:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI & Authenticate
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.SFDX_AUTH_URL }}

      - name: Validate-Only Deploy to Integration Org
        run: |
          # This will perform a dry-run (validate-only) deploy
          sf project deploy start \
            --source-dir force-app/main/default \
            --dry-run 